=== JDGuevar/Multi/IdeaProjects/PrimerAño/Celler/celler.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="celler">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="productes"/>
                <xs:element ref="clients"/>
                <xs:element ref="factures"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="productes">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="12" minOccurs="12" ref="producte"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="producte">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="codi" use="required" type="_codi_producte_"/>
                    <xs:attribute name="preu" use="required" type="_preu_"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="_codi_producte_">
        <xs:restriction base="xs:ID">
            <xs:pattern value="[BNR][1235]"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="_preu_">
        <xs:restriction base="xs:decimal">
            <xs:enumeration value="1.50"/>
            <xs:enumeration value="2.50"/>
            <xs:enumeration value="3.50"/>
            <xs:enumeration value="5.50"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="clients">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="client"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="client">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nom" type="xs:string"/>
                <xs:element maxOccurs="2" name="telefon" type="_telefon_"/>
            </xs:sequence>
            <xs:attribute name="codi" use="required" type="_codi_client_"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="_telefon_">
        <xs:restriction base="xs:string">
            <xs:pattern value="[6-9]\d{2} \d{3} \d{3}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="_codi_client_">
      <xs:restriction base="xs:ID">
        <xs:pattern value="C\d{5}"/>
      </xs:restriction>
    </xs:simpleType>

    <xs:element name="factures">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="factura"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="factura">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="comprador"/>
                <xs:element maxOccurs="12" ref="unitats"/>
            </xs:sequence>
            <xs:attribute name="codi" use="required" type="_codi_factura_"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="_codi_factura_">
        <xs:restriction base="xs:ID">
            <xs:pattern value="F\d{6}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="comprador">
        <xs:complexType>
            <xs:attribute name="codi" use="required" type="_codi_comprador_"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="_codi_comprador_">
        <xs:restriction base="xs:IDREF">
            <xs:pattern value="C\d{5}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="unitats">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:integer">
                    <xs:attribute name="codi" use="required" type="_codi_unitats_"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="_codi_unitats_">
        <xs:restriction base="xs:IDREF">
            <xs:pattern value="[BNR][1235]"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== JDGuevar/Multi/IdeaProjects/PrimerAño/CellerMaker/out/production/CellerMaker/celler.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="celler.css"?>
<celler xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="celler.xsd">
<productes>
<producte codi="B1" preu="1.50">Vi blanc botella d'1 litre</producte>
<producte codi="B2" preu="2.50">Vi blanc botella de 2 litres</producte>
<producte codi="B3" preu="3.50">Vi blanc garrafa de 3 litres</producte>
<producte codi="B5" preu="5.50">Vi blanc garrafa de 5 litres</producte>
<producte codi="N1" preu="1.50">Vi negre botella d'1 litre</producte>
<producte codi="N2" preu="2.50">Vi negre botella de 2 litres</producte>
<producte codi="N3" preu="3.50">Vi negre garrafa de 3 litres</producte>
<producte codi="N5" preu="5.50">Vi negre garrafa de 5 litres</producte>
<producte codi="R1" preu="1.50">Vi rosat botella d'1 litre</producte>
<producte codi="R2" preu="2.50">Vi rosat botella de 2 litres</producte>
<producte codi="R3" preu="3.50">Vi rosat garrafa de 3 litres</producte>
<producte codi="R5" preu="5.50">Vi rosat garrafa de 5 litres</producte>
</productes>
<clients>
<client codi="C00001">
<nom>Rey Gallego, Victoriano Ali</nom>
<telefon>762 047 568</telefon>
<telefon>850 476 646</telefon>
</client>
<client codi="C00002">
<nom>Heredia Beltran, Mustapha</nom>
<telefon>687 211 518</telefon>
</client>
<client codi="C00003">
<nom>Avila Escudero, Alicia Elisa</nom>
<telefon>770 749 421</telefon>
</client>
<client codi="C00004">
<nom>Moreno Valero, Aida Lola</nom>
<telefon>765 687 138</telefon>
<telefon>724 783 974</telefon>
</client>
<client codi="C00005">
<nom>Simon Bernal, Yaiza Francisca</nom>
<telefon>649 128 450</telefon>
<telefon>769 299 753</telefon>
</client>
<client codi="C00006">
<nom>Ferrer Contreras, Josefina Remedios</nom>
<telefon>659 711 694</telefon>
</client>
<client codi="C00007">
<nom>Romero Montero, Juana Berta</nom>
<telefon>699 621 533</telefon>
<telefon>920 291 835</telefon>
</client>
<client codi="C00008">
<nom>Franco Sanz, Lucas Alex</nom>
<telefon>775 342 874</telefon>
</client>
<client codi="C00009">
<nom>Mesa Carrasco, Roman</nom>
<telefon>741 410 004</telefon>
<telefon>612 341 890</telefon>
</client>
<client codi="C00010">
<nom>Estevez Alonso, Emilio Jose</nom>
<telefon>620 143 553</telefon>
</client>
<client codi="C00011">
<nom>Luna Estevez, Elias Oriol</nom>
<telefon>656 379 013</telefon>
<telefon>637 430 544</telefon>
</client>
<client codi="C00012">
<nom>Santiago De, Pere Carles</nom>
<telefon>767 571 839</telefon>
<telefon>684 554 363</telefon>
</client>
<client codi="C00013">
<nom>Cano La, Helena Celia</nom>
<telefon>666 774 941</telefon>
<telefon>821 610 771</telefon>
</client>
<client codi="C00014">
<nom>Ramos Izquierdo, Hector</nom>
<telefon>602 270 164</telefon>
<telefon>635 704 237</telefon>
</client>
<client codi="C00015">
<nom>Heredia Simon, Erik</nom>
<telefon>669 798 261</telefon>
<telefon>761 308 397</telefon>
</client>
<client codi="C00016">
<nom>Hidalgo Manzano, Estrella Andrea</nom>
<telefon>668 208 044</telefon>
</client>
<client codi="C00017">
<nom>Marti Saez, Ascension Abril</nom>
<telefon>748 466 232</telefon>
</client>
<client codi="C00018">
<nom>Gimenez Carrillo, Mercedes</nom>
<telefon>798 493 181</telefon>
</client>
<client codi="C00019">
<nom>Herrero Ruiz, Samuel Christian</nom>
<telefon>700 347 656</telefon>
</client>
<client codi="C00020">
<nom>Escobar Gomez, Ruben Marc</nom>
<telefon>731 667 257</telefon>
<telefon>998 661 920</telefon>
</client>
<client codi="C00021">
<nom>Diez Camacho, Fatima Nadia</nom>
<telefon>775 831 373</telefon>
<telefon>899 684 829</telefon>
</client>
<client codi="C00022">
<nom>Simon Garcia, Tatiana Esperanza</nom>
<telefon>680 420 980</telefon>
<telefon>948 488 872</telefon>
</client>
<client codi="C00023">
<nom>Castillo Esteban, Joana Cristina</nom>
<telefon>795 849 603</telefon>
<telefon>644 806 395</telefon>
</client>
<client codi="C00024">
<nom>Vera, Remedios Marta</nom>
<telefon>755 761 661</telefon>
<telefon>746 281 828</telefon>
</client>
<client codi="C00025">
<nom>Galan Guerra, Ainara Ainhoa</nom>
<telefon>780 797 446</telefon>
</client>
<client codi="C00026">
<nom>Mateos Martin, Clara Victoria</nom>
<telefon>781 415 181</telefon>
<telefon>710 979 697</telefon>
</client>
<client codi="C00027">
<nom>Soto Manzano, Jacinto Bautista</nom>
<telefon>611 913 918</telefon>
</client>
<client codi="C00028">
<nom>Duran Crespo, Sofia Yolanda</nom>
<telefon>692 275 582</telefon>
</client>
<client codi="C00029">
<nom>Calderon Pereira, Antonio Roman</nom>
<telefon>762 429 857</telefon>
<telefon>744 468 661</telefon>
</client>
<client codi="C00030">
<nom>Valero Mateo, Antoni</nom>
<telefon>730 450 442</telefon>
<telefon>728 102 928</telefon>
</client>
<client codi="C00031">
<nom>Miranda Martinez, Clara Judith</nom>
<telefon>669 220 650</telefon>
</client>
<client codi="C00032">
<nom>Pastor Gimenez, Nerea</nom>
<telefon>679 860 006</telefon>
</client>
<client codi="C00033">
<nom>Rivero Ramos, Jose Tatiana</nom>
<telefon>641 361 359</telefon>
<telefon>795 849 194</telefon>
</client>
<client codi="C00034">
<nom>Castro, Ernesto Leonardo</nom>
<telefon>608 035 791</telefon>
</client>
<client codi="C00035">
<nom>Guillen, Pilar Tamara</nom>
<telefon>710 367 365</telefon>
<telefon>928 065 649</telefon>
</client>
<client codi="C00036">
<nom>Roman Mora, Isabel Irene</nom>
<telefon>739 054 379</telefon>
</client>
<client codi="C00037">
<nom>Tomas Carrasco, Julia</nom>
<telefon>775 538 356</telefon>
<telefon>694 530 413</telefon>
</client>
<client codi="C00038">
<nom>Rodriguez, Inmaculada</nom>
<telefon>705 301 022</telefon>
</client>
<client codi="C00039">
<nom>Rivero Bravo, Diego Jairo</nom>
<telefon>748 807 617</telefon>
</client>
<client codi="C00040">
<nom>Arroyo Tomas, Guillem Jeronimo</nom>
<telefon>684 635 908</telefon>
<telefon>687 214 056</telefon>
</client>
<client codi="C00041">
<nom>Cortes Pardo, Antonio Manuel</nom>
<telefon>771 202 547</telefon>
</client>
<client codi="C00042">
<nom>Palacios Carmona, Jacinto Fernando</nom>
<telefon>620 461 831</telefon>
<telefon>965 811 038</telefon>
</client>
<client codi="C00043">
<nom>Pe√±a, Lara</nom>
<telefon>746 706 520</telefon>
</client>
<client codi="C00044">
<nom>Alarcon Gimenez, Soledad Alma</nom>
<telefon>747 715 127</telefon>
<telefon>878 392 275</telefon>
</client>
<client codi="C00045">
<nom>Acosta Escobar, Lola Encarnacion</nom>
<telefon>767 070 049</telefon>
<telefon>973 059 484</telefon>
</client>
<client codi="C00046">
<nom>Rico Luna, Amaia Rebeca</nom>
<telefon>751 337 837</telefon>
<telefon>756 954 543</telefon>
</client>
<client codi="C00047">
<nom>Arroyo Lozano, Enrique Damian</nom>
<telefon>655 048 009</telefon>
</client>
<client codi="C00048">
<nom>Aranda, Leonardo Gonzalo</nom>
<telefon>707 648 564</telefon>
<telefon>933 108 536</telefon>
</client>
<client codi="C00049">
<nom>Aguilera Carmona, Florencio</nom>
<telefon>659 454 214</telefon>
</client>
<client codi="C00050">
<nom>Galvez Marti, Alfredo Alberto</nom>
<telefon>705 630 918</telefon>
<telefon>925 453 144</telefon>
</client>
</clients>
<factures>
<factura codi="F000001">
<comprador codi="C00046"/>
<unitats codi="B1">3</unitats>
<unitats codi="B3">1</unitats>
<unitats codi="N3">3</unitats>
<unitats codi="R1">2</unitats>
<unitats codi="R2">3</unitats>
<unitats codi="R5">5</unitats>
</factura>
<factura codi="F000002">
<comprador codi="C00038"/>
<unitats codi="B1">3</unitats>
<unitats codi="B5">2</unitats>
<unitats codi="N1">4</unitats>
<unitats codi="N2">4</unitats>
<unitats codi="R2">5</unitats>
<unitats codi="R3">2</unitats>
<unitats codi="R5">3</unitats>
</factura>
<factura codi="F000003">
<comprador codi="C00014"/>
<unitats codi="B2">3</unitats>
<unitats codi="B3">4</unitats>
<unitats codi="N1">4</unitats>
<unitats codi="R2">1</unitats>
<unitats codi="R3">5</unitats>
</factura>
<factura codi="F000004">
<comprador codi="C00006"/>
<unitats codi="B2">5</unitats>
<unitats codi="N2">5</unitats>
<unitats codi="N5">5</unitats>
<unitats codi="R1">1</unitats>
<unitats codi="R2">1</unitats>
<unitats codi="R5">1</unitats>
</factura>
<factura codi="F000005">
<comprador codi="C00020"/>
<unitats codi="B1">1</unitats>
<unitats codi="B2">3</unitats>
<unitats codi="B5">3</unitats>
<unitats codi="N2">4</unitats>
<unitats codi="N3">4</unitats>
<unitats codi="N5">2</unitats>
<unitats codi="R2">2</unitats>
<unitats codi="R3">4</unitats>
</factura>
<factura codi="F000006">
<comprador codi="C00025"/>
<unitats codi="B3">5</unitats>
<unitats codi="N1">2</unitats>
<unitats codi="N5">5</unitats>
<unitats codi="R1">4</unitats>
<unitats codi="R2">1</unitats>
<unitats codi="R5">1</unitats>
</factura>
<factura codi="F000007">
<comprador codi="C00040"/>
<unitats codi="B2">1</unitats>
<unitats codi="N1">5</unitats>
<unitats codi="N2">5</unitats>
<unitats codi="N5">1</unitats>
<unitats codi="R3">1</unitats>
<unitats codi="R5">2</unitats>
</factura>
<factura codi="F000008">
<comprador codi="C00001"/>
<unitats codi="B1">2</unitats>
<unitats codi="B2">2</unitats>
<unitats codi="B3">2</unitats>
<unitats codi="N1">2</unitats>
<unitats codi="N2">4</unitats>
<unitats codi="N3">4</unitats>
<unitats codi="R1">2</unitats>
</factura>
<factura codi="F000009">
<comprador codi="C00015"/>
<unitats codi="B1">5</unitats>
<unitats codi="B2">4</unitats>
<unitats codi="B5">3</unitats>
<unitats codi="N2">2</unitats>
<unitats codi="N3">4</unitats>
<unitats codi="N5">5</unitats>
<unitats codi="R5">3</unitats>
</factura>
<factura codi="F000010">
<comprador codi="C00029"/>
<unitats codi="B1">2</unitats>
<unitats codi="B3">2</unitats>
<unitats codi="N5">2</unitats>
<unitats codi="R1">1</unitats>
</factura>
<factura codi="F000011">
<comprador codi="C00031"/>
<unitats codi="B2">2</unitats>
<unitats codi="B5">4</unitats>
<unitats codi="N1">1</unitats>
<unitats codi="N2">1</unitats>
<unitats codi="R1">3</unitats>
<unitats codi="R2">1</unitats>
</factura>
<factura codi="F000012">
<comprador codi="C00025"/>
<unitats codi="B1">1</unitats>
